# Use an official Nginx image as the base
FROM nginx:alpine

# Set working directory
WORKDIR /usr/share/nginx/html

# Copy the frontend files
COPY frontend/ .
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf  
# Copy custom Nginx configuration (optional, if needed)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]